project:
  type: website
  output-dir: docs

website:
  title: "WiDS Tucson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Conference"
        menu: 
          - text: "2023"
            href: Conference/conf2023.qmd
          - text: "2022"
            href: Conference/conf2022.markdown
      - text: "Datathon"
        href: datathon.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true



