project:
  type: website
  output-dir: docs

website:
  navbar:
    pinned: true
    title: " "
    logo-alt: "TBD"
    right:
      - text: "About"
        href: about.qmd
      - text: "2024 Conference"
        href: conf2024.qmd
      - text: "2024 Speakers"
        href: speakers2024.qmd
      - text: "2024 Data Blitz"
        href: datablitz2024.qmd
      - text: "Meeting Archive"
        href: archive.qmd
      - text: "Datathon Workshop"
        href: datathon2024.qmd    
      - text: "About the Organizers"
        href: organizers.qmd
      - text: "Event Sponsors"
        href: sponsors.qmd
      - text: "Join the Community"
        href: community.qmd
      - text: "Code of Conduct"
        href: conduct.qmd
      - icon: github
        href: https://github.com/wids-tucson/wids-tucson.github.io

format:
  html:
    theme: styles.css
    toc: true

resources:
  - CNAME
