project:
  type: website
  output-dir: docs

website:
  favicon: images/logo.png
  navbar:
    title: "WiDS Tucson"
    logo: images/logo.png
    logo-alt: "The Women in Data Science logo featuring a head with long straight hair facing to the left with hair blowing to the right"
    left:
      - text: "Conference"
        menu:
          - text: "About"
            href: conf.qmd
          - text: "2023 Conference"
            href: conf2023.qmd
          - text: "Meeting Archive"
            href: archive.qmd
      - text: "Datathon"
        href: datathon.qmd
    right:
      - text: "Community"
        menu:
          - text: "About the Organizers"
            href: about.qmd
          - text: "Event Sponsors"
            href: sponsors.qmd
          - text: "Join the Community"
            href: community.qmd
          - text: "Code of Conduct"
            href: conduct.qmd
      - icon: github
        href: https://github.com/wids-tucson/wids-tucson.github.io

format:
  html:
    theme: styles.css
    toc: true



