project:
  type: website
  output-dir: docs

website:
  favicon: images/logo.png
  navbar:
    title: "WiDS Tucson"
    logo: images/logo.png
    logo-alt: "The wids head logo"
    left:
      - text: "Conference"
        menu: 
          - text: "2023"
            href: Conference/conf2023.qmd
          - text: "2022"
            href: Conference/conf2022.markdown
      - text: "Datathon"
        href: datathon.qmd
    right:
      - text: "Community"
        menu:
          - text: "Join the Community"
            href: community.qmd
          - text: "Code of Conduct"
            href: conduct.qmd
      - icon: github
        href: https://github.com/wids-tucson/wids-tucson.github.io

format:
  html:
    theme: styles.css
    toc: true



